---
Standards:
  -
    Title: Industry Prep Fridays
    Description: "Activities and Lessons for Industry Prep Fridays"
    UID: 2f1f90e3-3a7e-4647-bc39-47863a981d0e
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 38431de4-5a77-4820-8c9c-c30877c3d892
        Path: /industry-prep-fridays/industry-prep-fridays.instructor.md
      -
        Type: Instructor
        UID: 1763bf75
        Path: /industry-prep-fridays/activity-git-collaboration.instructor.md
      -
        Type: Instructor
        UID: d1ede537-7930-4f83-9b13-2263081b3b2d
        Path: /industry-prep-fridays/activity-code-coverage.instructor.md 
      -
        Type: Lesson
        UID: defb503c-4b0e-4cbc-b524-8b912c4ebe35
        Path: /industry-prep-fridays/intro-industry-prep-fridays.md
      -
        Type: Lesson
        UID: 500d9781
        Path: /industry-prep-fridays/activity-git-collaboration.md
      -
        Type: Resource
        UID: tSg96d
        Path: /industry-prep-fridays/activity-git-history.md 
      -
        Type: Lesson
        UID: 29c5d18e-7412-4bb3-aa03-dd24137cfe16
        Path: /industry-prep-fridays/activity-code-coverage.md  
      -
        Type: Lesson
        UID: b9f55320-922f-4ded-8240-0c7953fe2de8
        Path: /industry-prep-fridays/asking-questions-reading-documentation.md
  -
    Title: Algorithm Practice Sessions
    Description: "Algorithm Practice Sessions"
    UID: a0b2c923-352c-488e-927b-6534bae1ce03
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: e4623cca-e53f-4812-b2e5-af735be00cbb
        Path: /algorithms/algorithm-practice-sessions.md
  -
    Title: Python Mob Programming
    Description: "Activity: Python Mob Programming"
    UID: 80fa67885c3e94ef1bd67fbf6b9f7b3a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: d06d453ef18964ae67d0bc22e16876bf
        Path: /python-mob-programming/activity-python-mob-programming.instructor.md
      -
        Type: Lesson
        UID: 81865d51eb17b709fe709ed5fa254ae8
        Path: /python-mob-programming/activity-python-mob-programming.md
  -
    Title: Interview Questions
    Description: "Activity: Interview Question"
    UID: 091e224a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: fa72c177
        Path: /interview-questions/activity-interview-questions.instructor.md
      -
        Type: Lesson
        UID: 709b6f67
        Path: /interview-questions/activity-interview-questions.md
  -
    Title: Career Paths
    Description: "Activity: Specialized Fields Jigsaw"
    UID: 1432a704
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 84bfd595
        Path: /career-paths/activity-specialized-fields-jigsaw.instructor.md
      -
        Type: Lesson
        UID: d4000c00
        Path: /career-paths/activity-specialized-fields-jigsaw.md
  -
    Title: Communities
    Description: "Activity: Event and Media Recommendations"
    UID: a1628466
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 8402621c
        Path: /communities/activity-event-and-media-recommendations.instructor.md
      -
        Type: Lesson
        UID: 69e158e3
        Path: /communities/activity-event-and-media-recommendations.md
  -
    Title: Current Events
    Description: "Activity: Current Events"
    UID: 0e6daa6e
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: a91cb97e
        Path: /current-events/activity-current-events.instructor.md
      -
        Type: Lesson
        UID: 5e3099cb
        Path: /current-events/activity-current-events.md
  -
    Title: Curriculum Wrap-Up
    Description: "Activity: Think, Pair, Share, Review"
    UID: a8b80293
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 46add73c
        Path: /curriculum-wrap-up/activity-think-pair-share-review.instructor.md
      -
        Type: Lesson
        UID: 586453bd
        Path: /curriculum-wrap-up/activity-think-pair-share-review.md
