---
Standards:
  -
    Title: Python Mob Programming
    Description: "Activity: Python Mob Programming"
    UID: 80fa67885c3e94ef1bd67fbf6b9f7b3a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: d06d453ef18964ae67d0bc22e16876bf
        Path: /python-mob-programming/activity-python-mob-programming.instructor.md
      -
        Type: Lesson
        UID: 81865d51eb17b709fe709ed5fa254ae8
        Path: /python-mob-programming/activity-python-mob-programming.md
  -
    Title: Current Events
    Description: "Activity: Current Events"
    UID: 0e6daa6e
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: a91cb97e
        Path: /current-events/activity-current-events.instructor.md
      -
        Type: Lesson
        UID: 5e3099cb
        Path: /current-events/activity-current-events.md
