---
Standards:
  -
    Title: Industry Prep Fridays
    Description: "Activities and Lessons for Industry Prep Fridays"
    UID: 2f1f90e3-3a7e-4647-bc39-47863a981d0e
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 38431de4-5a77-4820-8c9c-c30877c3d892
        Path: /industry-prep-fridays/instructor-unit-1-industry-prep.md
      -
        Type: Instructor
        UID: 3c84a434-1b17-45f5-b908-332bd84c5629
        Path: /industry-prep-fridays/instructor-unit-2-industry-prep.md
      -
        Type: Lesson
        UID: defb503c-4b0e-4cbc-b524-8b912c4ebe35
        Path: /industry-prep-fridays/intro-industry-prep-fridays.md
      -
        Type: Lesson
        UID: 500d9781
        Path: /industry-prep-fridays/activity-git-collaboration.md
      -
        Type: Resource
        UID: tSg96d
        Path: /industry-prep-fridays/activity-git-history.md 
      -
        Type: Lesson
        UID: 29c5d18e-7412-4bb3-aa03-dd24137cfe16
        Path: /industry-prep-fridays/activity-code-coverage.md  
      -
        Type: Lesson
        UID: b9f55320-922f-4ded-8240-0c7953fe2de8
        Path: /industry-prep-fridays/asking-questions-reading-documentation.md
      -
        Type: Lesson
        UID: 9487cdd3-e1c9-44dd-bc15-3fe9ffbedcbe
        Path: /industry-prep-fridays/git-branching-merge-carnival.md
      -
        Type: Lesson
        UID: b98017a9-eaf9-4890-8538-f37eb30d74c3
        Path: /industry-prep-fridays/activity-code-reviews.md
  -
    Title: Algorithm Practice Sessions
    Description: "Algorithm Practice Sessions"
    UID: a0b2c923-352c-488e-927b-6534bae1ce03
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: e9dee1ea-755a-4e4b-8ad6-038e40e0c0e7
        Path: /algorithms/introduction.md
      -
        Type: Lesson
        UID: e4623cca-e53f-4812-b2e5-af735be00cbb
        Path: /algorithms/algorithm-practice-sessions-1.md
      -
        Type: Lesson
        UID: cac74e68-dde3-46b7-9019-0a84431715b2
        Path: /algorithms/algorithm-practice-sessions-2.md
      -
        Type: Lesson
        UID: 1f13aa7b-2b9b-4af7-914c-b51caf4ff74d
        Path: /algorithms/algorithm-practice-sessions-3.md

      -
        Type: Lesson
        UID: 3e90d2b8-07f4-4f8b-b6ae-c230f43a4382
        Path: /algorithms/algorithm-practice-sessions-4.md

      -
        Type: Lesson
        UID: 950ac214-d0d6-4dec-9fe0-97562aaec849
        Path: /algorithms/algorithm-practice-sessions-5.md

      -
        Type: Lesson
        UID: c1682ba4-6be0-4eff-a905-2a6c793fc06a
        Path: /algorithms/algorithm-practice-sessions-6.md

      -
        Type: Lesson
        UID: 7307dbdb-22f4-428f-8ca3-0ea5f4d326b7
        Path: /algorithms/algorithm-practice-sessions-7.md

      -
        Type: Lesson
        UID: c2cfe1ac-f669-49cf-bee2-4a422206613a
        Path: /algorithms/algorithm-practice-sessions-8.md

      -
        Type: Lesson
        UID: 1b1c4486-178d-4717-9e19-4a52a6c2b3a3
        Path: /algorithms/algorithm-practice-sessions-9.md

      -
        Type: Lesson
        UID: a2e5029e-1ad7-4497-8338-9fc08390ad0f
        Path: /algorithms/algorithm-practice-sessions-10.md

      -
        Type: Lesson
        UID: 8c55cfdb-9c1b-4d75-88f1-d98d9a769018
        Path: /algorithms/algorithm-practice-sessions-11.md
  -
    Title: Python Mob Programming
    Description: "Activity: Python Mob Programming"
    UID: 80fa67885c3e94ef1bd67fbf6b9f7b3a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: d06d453ef18964ae67d0bc22e16876bf
        Path: /python-mob-programming/activity-python-mob-programming.instructor.md
      -
        Type: Lesson
        UID: 81865d51eb17b709fe709ed5fa254ae8
        Path: /python-mob-programming/activity-python-mob-programming.md
  -
    Title: Interview Questions
    Description: "Activity: Interview Question"
    UID: 091e224a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: fa72c177
        Path: /interview-questions/activity-interview-questions.instructor.md
      -
        Type: Lesson
        UID: 709b6f67
        Path: /interview-questions/activity-interview-questions.md
  -
    Title: Career Paths
    Description: "Activity: Specialized Fields Jigsaw"
    UID: 1432a704
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 84bfd595
        Path: /career-paths/activity-specialized-fields-jigsaw.instructor.md
      -
        Type: Lesson
        UID: d4000c00
        Path: /career-paths/activity-specialized-fields-jigsaw.md
  -
    Title: Communities
    Description: "Activity: Event and Media Recommendations"
    UID: a1628466
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 8402621c
        Path: /communities/activity-event-and-media-recommendations.instructor.md
      -
        Type: Lesson
        UID: 69e158e3
        Path: /communities/activity-event-and-media-recommendations.md
  -
    Title: Current Events
    Description: "Activity: Current Events"
    UID: 0e6daa6e
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: a91cb97e
        Path: /current-events/activity-current-events.instructor.md
      -
        Type: Lesson
        UID: 5e3099cb
        Path: /current-events/activity-current-events.md
  -
    Title: Curriculum Wrap-Up
    Description: "Activity: Think, Pair, Share, Review"
    UID: a8b80293
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 46add73c
        Path: /curriculum-wrap-up/activity-think-pair-share-review.instructor.md
      -
        Type: Lesson
        UID: 586453bd
        Path: /curriculum-wrap-up/activity-think-pair-share-review.md
